name: "voice_type_recognition"
platform: "tensorflow_savedmodel"
max_batch_size: 8

input [
  {
    name: "conv2d_input"
    data_type: TYPE_FP32
    dims: [ 128, 128, 1 ]
  }
]
output [
  {
    name: "activation_4"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]