entryPoint: main
name: Example Project
connection:
  main:
    port: 8085
    path: /process/algo/{{input.algo}}/
    method: POST
    body:
      type: binary
      input: "{{input.image}}"
input:
  algo:
    label: "Algorithm"
    type: "select"
    values:
      - "Fast"
      - "Accurate"
  image:
    label: "Image"
    type: "image" # image, input, slider, textarea, select, multiselect, checkbox, radio
    values:
      accepts:
          - "image/jpg"
          - "image/png"
      type: binary # binary, base64
output:
  description:
    label: "List of all Elements"
    type: "list"
    format:
      labelName: "{{cmd.json(connection.main/dense_2[]/name)}}"
      labelValue: "{{cmd.json(connection.main/dense_2[]/certainty)}}"
      representation: "discretePercentageBar" # percentageBar, discretePercentageBar, text