version: "3.9"
services:
  web:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./src:/app
  triton:
    image: nvcr.io/nvidia/tritonserver:21.04-py3
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
        - ./models:/models
    command: tritonserver --model-repository=/models --model-control-mode=explicit